### ISSUE TITLE
Add master dynamic background image

### ISSUE THREAD

**Issue by msp1974** [dinki/view_assist_integration#112]
As the master config functionality is implemented, this now allows for centalised management of things, such as a master dynamic background image.

To this end, we should implement a master set of dynamic background options (master sequenced local image, master random local image, master random unsplash image) which will allow all devices have the same background and change at the same time.

This will then allow:

- Devices to have the same dynamic background (this enhancement)
- Devices grouped to have the same dynamic background (existing)
- Devices to have individual dynamic backgrounds (existing)
- Combinations of the above

**Comment by msp1974** [comment]
No

**Comment by jeroenterheerdt** [comment]
I just migrated to the integration and updated all the cards to have dynamic backgrounds, so would be great if there was one setting on the integration.

**Comment by jeroenterheerdt** [comment]
Thanks for sharing the docs link, but I don't think this is applied to all views though. For example, the list view seem to have static backgrounds that are not dependent on the master or satellite configuration. I was hoping if I set the master or satellite configuration, all views on the satellite(s) would adopt that background...?

See here: https://github.com/dinki/View-Assist/blob/main/View%20Assist%20dashboard%20and%20views/views/list/list.yaml:

```
type: custom:button-card
variables:
  listcardversion: 1.0.2
  var_list: >-
    [[[ try {return
    hass.states[variables.var_assistsat_entity].attributes.list} catch {
    return  "todo.shopping_list"}]]]
  background: /view_assist/dashboard/infobackground.png
template:
  - variable_template
  - body_template
styles:
  card:
    - background: '[[[ return `center / cover no-repeat url(${variables.background})` ]]]'
    - background-size: cover
```

That results in the background being set to `infobackground.png` not whatever the master or satellite config was.
