### ISSUE TITLE
Is the get_target_satellite service needed anymore?

### ISSUE THREAD

**Issue by msp1974** [dinki/view_assist_integration#51]
With the VA entity now stored in localStorage and added to a dashboard variable and the VA template functions , do we get the target satellite from

```
states[variables.var_assistsat_entity].attributes.mic_device
```
in javascript for the card and
```
hass.state_attr(va_entity([SATELLITE_DEVICE_ID]), "mic_device")
```
in a BP script

and therefore we can remove the get_target_satellite service?

**Comment by dinki** [comment]
```
- action: view_assist.get_target_satellite
  data:
    device_id: "{{ trigger.device_id }}"
  response_variable: target_satellite
- variables:
    target_satellite_device: "{{ target_satellite.target_satellite[0] }}"
    target_mediaplayer_device: '{{ state_attr(target_satellite_device, ''mediaplayer_device'')}}'
    target_satellite_device_type: '{{ state_attr(target_satellite_device, ''type'')}}'
```

Here's how I am using this on all BPs.  Are you saying that this could be written like:

```
target_satellite_device: '{{ va_entity(trigger.device_id) }}'
target_mediaplayer_device: '{{ va_entity(trigger.device_id), "mediaplayer_device" }}'
target_satellite_device_type: '{{ va_entity(trigger.device_id), "type" }}'
```

If so, then yes.  I'll give it a quick test to confirm but looks like a better way to do things for sure.  Please confirm I'm seeing this correctly, I'll test and report back for removing.

**Comment by dinki** [comment]
Okay, looking at this closer:

```
  - variables:
      target_satellite_device: "{{ view_assist_entity(trigger.device_id) }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device')}}"
      target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type')}}"

```
This works great!  I agree that the get_target_satellite service can be removed.

Is there a way to get the other attributes using the view_assist_entity similar to what I was asking about above?  I'm fine with what I show here but just wondering if there is a better/cleaner way?

**Comment by msp1974** [comment]
This is the right way. I don't currently have it to provide an attribute. 

```
  - variables:
      target_satellite_device: "{{ view_assist_entity(trigger.device_id) }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device')}}"
      target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type')}}"
```
